kind: pipeline
name: default

platform: linux/arm

steps:
- name: docker  
  image: plugins/docker:linux-arm
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: cwilko/grafana-arm-url
    tags: latest